### PR TITLE
Updates to Accessory Information

### PR DESCRIPTION
**Pull request by rcoletti116**
**New**

1. Update config.schema.json to support Serial Number and Model entries.
2. Update platformAccessory.ts to support Serial Number characteristic. Having a unique serial number is important for certain HomeKit functions. This gives the user the ability to set one.

**Updates**

1. Update platformAccessory.ts with ability to set Model # from Config. I found that the device.info was incorrect or missing in some cases.

**Additional Notes**
I'm not sure if the firmware revision characteristic is working the way that you intend, but have not made changes. With what is present today no firmware details get set in HomeKit (for me at least). If I set either device.info.sw OR device.info.ver it does supply a value (tested locally). Could just be my experience, but curious of your thoughts. BTW - I hope you don't mind the PRs and suggestions.

### CODE REVIEW

**Comment by rcoletti116** [comment]
@bloomkd46 do you have any concerns with the PR?

**Comment by bloomkd46** [comment]
It looks fine, I'm just seeing if I can get it to retrieve the software version from the roomba. I also don't see the need to put in a custom model since it automatically detects it.

**Comment by bloomkd46** [comment]
When I add support for manually adding Roomba's I will add the ability to manually change the model, software version, and many other things

**Comment by rcoletti116** [comment]
> I also don't see the need to put in a custom model since it automatically detects it. 

In my case it doesn’t detect it correctly. I get ‘98-‘ when it should be 980. A minor thing, but still worth addressing. 

The more pressing is serial number. The apps they do HomeKit backups check got unique serials to help with the backup/restore functions for groups, scenes, automations, etc…

**Comment by bloomkd46** [comment]
> The more pressing is serial number. The apps they do HomeKit backups check got unique serials to help with the backup/restore functions for groups, scenes, automations, etc…

just curious what app do you use that lets you back up scenes and devices?

**Comment by bloomkd46** [comment]
Also you might want to check out the beta version as they offer support for manual configuration of the model and serial number

**Comment by rcoletti116** [comment]
> just curious what app do you use that lets you back up scenes and devices?
I use Controller For HomeKit which has very granular backup and restore features.  Home+ also supports backups. It really comes in handy. 

I’ll check out the beta.

**Pull request closed without merging**
